name: Android CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        shell: bash
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;25.2.9519653" "cmake;3.22.1"
          yes | sdkmanager --licenses

      - name: Download Gradle 8.7
        shell: bash
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "${{ github.workspace }}/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v

      - name: Build Debug APK
        shell: bash
        run: gradle -Dorg.gradle.jvmargs="-Xmx4g" assembleDebug

      - name: Build Release APK
        shell: bash
        run: gradle -Dorg.gradle.jvmargs="-Xmx4g" assembleRelease

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
